### ISSUE TITLE
updating navigation property should use schema name not logical name

### ISSUE THREAD

**Issue by aappddeevv** [jlattimer/CRMRESTBuilder#28]
I had the case where I was creating a query that would update a navigation property:

logical name: publisher_contact
schema name: publisher_Contact

Payload:
{ ...
 "publisher_contact@odata.bind": "/contacts(xxxx)"
...} 

The property in the payload, I think, should have been the navigation property schema name, not logical, e.g. publisher_Contact instead of publisher_contact.

**Comment by jlattimer** [comment]
When I built the tool I incorrectly assumed the system metadata was the source of everything, as it turns out the data produced by the metadata url (https://org.crm.dynamics.com/api/data/v8.2/$metadata) url is. They are really close to being similar but not quite. 

Not sure if i'm going to fix this version or just address in the next version which will just be Web API in the v9 timeframe

**Comment by aappddeevv** [comment]
oh, I just saw that this is similar to #7. maybe they will fix this in v9, but I thought your code had an internal API that would make switching to the CSDL as the source of truth easier... but that may have been another code base somewhere. For my dynamicscli tool (node based) I had to pull the CSDL which takes awhile of course and stick everything into a metadata cache.

**Comment by jlattimer** [comment]
I'm thinking v9 isn't going to make the system metadata match the CSDL which pretty much means downloading all that content each time the tool loads :(

**Comment by eccountable** [comment]
I am using version 2.6.0.0. I generated a Create WebApi call on a custom entity, and got an error back from CRM (see below) which was because the code generated for a lookup field was not using the schema name. REST Builder generated 
`entity["tn_quoteid@odata.bind"] = "/quotes(" + FormLib.id + ")";`
when it should have been 
`entity["tn_QuoteId@odata.bind"] = "/quotes(" + FormLib.id + ")";`

Here is the error message:
"An error occurred while validating input parameters: Microsoft.OData.ODataException: An undeclared property 'tn_quoteid' which only has property annotations in the payload but no property value was found in the payload. In OData, only declared navigation properties and declared named streams can be represented as properties without values.
↵   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadUndeclaredProperty(IODataJsonLightReaderResourceState resourceState, String propertyName, Boolean propertyWithValue)
↵   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithoutValue(IODataJsonLightReaderResourceState resourceState, String propertyName)
↵   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass4_0.<ReadResourceContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
↵   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
↵   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)
↵   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)
↵   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector propertyAndAnnotationCollector)
↵   at Microsoft.OData.ODataReaderCore.ReadImplementation()
↵   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
↵   at System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)
↵   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
↵   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)"

**Comment by daryllabar** [comment]
@jlattimer, @eccountable is right, this is still not working in 2.6.0.0
